### ISSUE TITLE
Inconsistent tolerance type in qr_fact within zipper function

### ISSUE THREAD

**Issue by annamariadziubyna** [euro-hpc-pl/SpinGlassTensors.jl#23]
There is an inconsistency in the `zipper` function related to the `qr_fact` method ([here](https://github.com/euro-hpc-pl/SpinGlassTensors.jl/blob/master/src/zipper.jl)). The tolerance value is hard-coded multiple times as `0.0` (of type `Float64`). However, when invoking `qr_fact` ([here](https://github.com/euro-hpc-pl/SpinGlassTensors.jl/blob/master/src/linear_algebra_ext.jl)), the tolerance parameter is typed, and it can also accept `Float32`, which causes an error while testing Pegasus with `Float32`. Can we introduce a type parameter in the `zipper` function?

**Comment by lpawela** [comment]
What is an MWE of this issue?

**Comment by annamariadziubyna** [comment]
This is a test showing that the procedure works for small pathological Pegasus with Float64 but does not work for Float32: 
`@testset "Small pathological pegasus instance has the correct spectrum for all types" begin

    m, n, t = 3, 4, 1

    β = 0.5
    bond_dim = 8
    mstates = 10
    instance = "$(@__DIR__)/instances/pathological/pegasus_3_4_1.txt"

    iter = 2
    δp = 0.0
    MAX_SWEEPS = 0
    VAR_TOL = 1E-16
    TOL_SVD = 1E-16
    ITERS_SVD = 2
    ITERS_VAR = 1
    DTEMP_MULT = 2
    METHOD = :psvd_sparse
    Strategy = Zipper
    Sparsity = Sparse
    Layout = GaugesEnergy
    transform = all_lattice_transformations[1]
    ig = ising_graph(instance)
    cl_h = clustered_hamiltonian(
        ig,
        spectrum = full_spectrum,
        cluster_assignment_rule = pegasus_lattice((m, n, t)),
    )

    Gauge = NoUpdate
    for T in [Float64, Float32]
        println("=========")
        println("type ", T)
        energies = Vector{T}[]
        params = MpsParameters{T}(bond_dim, T(VAR_TOL), MAX_SWEEPS, T(TOL_SVD), ITERS_SVD, ITERS_VAR, DTEMP_MULT, METHOD)
        search_params = SearchParameters(mstates, δp)

        net = PEPSNetwork{SquareCrossDoubleNode{Layout},Sparsity,T}(m, n, cl_h, transform)
        ctr = MpsContractor{Strategy,Gauge,T}(
            net,
            T[β/8, β/4, β/2, β],
            :graduate_truncate,
            params;
            onGPU = onGPU,
        )
        sol, s = low_energy_spectrum(ctr, search_params)
        @test eltype(sol.energies) == T
        println(sol.energies[1])
        clear_memoize_cache()
    end
end`

**Comment by lpawela** [comment]
IS this the only case with errors with `Float32`?

**Comment by annamariadziubyna** [comment]
There appears to be an issue with `is_left_normalized` when using the version of the algorithm with `Float32`. Several functions, including the `zipper` and `variational_compress`, assert `is_left_normalized`. The problem might be related to tolerance issues with `isapprox` in `is_left_normalized`. Here, minimal case is Pegasus P4 - for some transforms it works, for some it doesn't. 
`@testset "Small pathological pegasus instance has the correct spectrum for all types" begin

    m, n, t = 3, 3, 3

    β = 0.5
    bond_dim = 8
    mstates = 10
    instance = "$(@__DIR__)/instances/pegasus_random/P4/RCO/SpinGlass/001_sg.txt"

    iter = 2
    δp = 0.0
    MAX_SWEEPS = 0
    VAR_TOL = 1E-16
    TOL_SVD = 1E-16
    ITERS_SVD = 2
    ITERS_VAR = 1
    DTEMP_MULT = 2
    METHOD = :psvd_sparse
    Strategy = Zipper
    Sparsity = Sparse
    Layout = GaugesEnergy
    ig = ising_graph(instance)
    cl_h = clustered_hamiltonian(
        ig,
        spectrum = full_spectrum,
        cluster_assignment_rule = pegasus_lattice((m, n, t)),
    )

    Gauge = NoUpdate
    for T in [Float32, ], transform in (all_lattice_transformations[1], all_lattice_transformations[3],)
        println("=========")
        println("type ", T)
        energies = Vector{T}[]
        params = MpsParameters{T}(bond_dim, T(VAR_TOL), MAX_SWEEPS, T(TOL_SVD), ITERS_SVD, ITERS_VAR, DTEMP_MULT, METHOD)
        search_params = SearchParameters(mstates, δp)

        net = PEPSNetwork{SquareCrossDoubleNode{Layout},Sparsity,T}(m, n, cl_h, transform)
        ctr = MpsContractor{Strategy,Gauge,T}(
            net,
            T[β/8, β/4, β/2, β],
            :graduate_truncate,
            params;
            onGPU = onGPU,
        )
        sol, s = low_energy_spectrum(ctr, search_params)
        @test eltype(sol.energies) == T
        println(sol.energies[1])
        clear_memoize_cache()
    end
end
`

**Comment by lpawela** [comment]
Solved by #24

**Comment by lpawela** [comment]
Solved by #24
