### ISSUE TITLE
MPS MPO multiplication issue

### ISSUE THREAD

**Issue by bartekGardas** [euro-hpc-pl/SpinGlassTensors.jl#9]
Consider, for instance,  `ψ = randn(MPS{Float64}, 4, 5, 2)` and `W = randn(MPO{Float64}, 4, 5, 2)`. Now compare, 
`ψ = W * ψ` and ψ *= W. Obviously, both should produce the same result. However, the latter does not work at all - could we fix that?

**Comment by lpawela** [comment]
This is expected. `ψ *=  W` is in fact a shorthand for `ψ = ψ * W`. As this operation is ill defined it is not supported.

**Comment by bartekGardas** [comment]
Well, ψ = ψ * W is actually well-defined but not defined (or rather defined by convention the other way around) in our repo. Can we make ψ *= W a shorthand for ψ = W * ψ?
